# Generated by Django 2.2 on 2020-08-22 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricão')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('end', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('dt_inicio', models.DateTimeField(verbose_name='Data de Inicio')),
                ('dt_fim', models.DateTimeField(blank=True, verbose_name='Data Final')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('rg', models.IntegerField(verbose_name='RG')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('dt_nasc', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Pessoa')),
                ('estado_civil', models.BooleanField(verbose_name='Estado Civil')),
                ('salario', models.FloatField(verbose_name='Salario')),
                ('va', models.FloatField(verbose_name='Vale alimentação')),
                ('vt', models.FloatField(verbose_name='Vale transporte')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_funcionario', to='core.Cargo')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obra_funcionario', to='core.Obra')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
            bases=('core.pessoa',),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateTimeField(verbose_name='Data de inicio')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_contrato', to='core.Cargo')),
                ('obra', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='obra_contrato', to='core.Obra')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_contrato', to='core.Funcionario')),
            ],
        ),
    ]
