# Generated by Django 2.2 on 2020-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Viuvo', 'Viuvo')], max_length=10, verbose_name='Estado Civil'),
        ),
    ]
