# Generated by Django 2.2 on 2020-08-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200822_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='telefone',
            field=models.CharField(max_length=255, verbose_name='Telefone'),
        ),
    ]
