# Generated by Django 2.2 on 2020-08-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='dt_nasc',
            field=models.DateField(),
        ),
    ]
